config/routes.rb
Rails.application.routes.draw do
	root "users#new"
	resources :posts do
		collection do   
			post :confirm
		end
	end
	resources :sessions, only: [:new, :create, :edit, :destroy]
	resources :users, only: [:new, :create, :edit, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :content, presence: true
	mount_uploader :image, ImageUploader
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord 
	validates :name,  presence: true, length: { maximum: 30 }
	validates :email, presence: true, length: { maximum: 255 },
										format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
	before_validation { email.downcase! }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper

	def authenticate_user
		if current_user == nil
			# flash[:notice] = t('notice.login_needed')
			flash[:notice] = "ログインが必要です。"
			redirect_to new_session_path
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, {only: [:new, :create, :edit, :confirm, :update, :show, :destroy]}
  def index
    @posts = Post.all
  end

  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path
    end
  end

  def show
    @post = current_user.posts.build(post_params)
  end

  def update
    @post = current_user.posts.build(post_params)
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user, {only: [:edit, :destroy]}
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user, {only: [:edit, :update]}

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
      session[:user_id] = @user.id
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
  
  def show
    @user = User.find(params[:id]) 
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		current_user.present?
	end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to 'Facebooook', posts_path %>
      </div>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if logged_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to '投稿する', new_post_path %></li>
          <li><%= link_to 'ホームに戻る', posts_path %></li>      
          <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "新しいアカウントを作成", new_user_path %></li>
          <li><%= link_to "ログイン", new_session_path %>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebooook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>
    <% if flash[:notice]%>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= flash[:notice] %>
        </div>
      </div>
    <% elsif flash[:danger] %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= flash[:danger] %>
        </div>
      </div>    
    <% end %>
    <div class='container'> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, url:confirm_posts_path) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.text_field :title, class: 'form-control',:placeholder => "タイトル" %>  
    <%= f.text_field :content, class: 'form-control input-lg',:placeholder => "メッセージをシェアしよう"%>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= f.file_field(:image,{:class => 'btn-primary'})  %>
    <%= f.hidden_field :image_cache　%>
    <div class="text-right">
      <%= f.submit("投稿する", class:"btn btn-primary") %>
      <%= link_to '戻る', posts_path, class:"btn btn-warning" %>
    <div>
<% end %>

app/views/posts/confirm.html.erb
<h1>投稿内容</h1>
<%= form_with(model: @post, url: posts_path, local: true) do |f| %>
  <div class="panel-body row">
    <p class="post-content"><%= @post.title %></p>
    <%= f.hidden_field :title %>
    <p class="post-content"><%= @post.content %></p>
    <%= f.hidden_field :content %>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= f.hidden_field :image_cache %>
  </div>
  <%= f.submit("投稿する", class:"btn btn-primary") %>
<% end %>
<%= form_with(model:@post, url:new_post_path, local:true, method:"get") do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <%= f.hidden_field :image_cache %>
  <%= f.submit("戻る", name: "back", class:"btn btn-warning") %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<p><%= notice %></p>
<% for post in @posts %>
  <div class="panel panel-default post-panel">
    <div class="panel-body row">
      <div class= "col-sm-1">
        <img src="/avatar.png" height="40px" widht="40px">
      </div>
      <div class= "col-sm-1">
        <%= post.user.name %>
      </div>
      <div class= "col-sm-10">
        <p class="post-content"><%= post.title %></p>
        <p class="post-content"><%= post.content %></p>
        <%= image_tag(post.image.url) if post.image && post.image.url %>
        <% if post.user.id == current_user.id %>
          <div class="post-links">                    
            <%= link_to edit_post_path(post.id) do %>
                <span class="glyphicon glyphicon-pencil g-links" aria-hidden="true"></span>                
            <% end %>
            <%= link_to post_path(post.id), method: :delete ,data: { confirm: '本当に削除してよろしいですか？' } do %>
                <span class="glyphicon glyphicon-trash g-links" aria-hidden="true"></span> 
            <% end %>        
          </div>
        <% end %>                           
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="post_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="post_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.file_field :image %>
  </div>
  <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<p>タイトル: <%= @post.title %></p>
<p>内容: <%= @post.content %></p>

app/views/users/edit.html.erb
<h1>プロフィール編集画面</h1>
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>

app/views/users/new.html.erb
<div class="row">
	<div class="col-md-6">
		<ul class="media-list">
			<li class="media">
				<img class="media-object media-left　img-responsive"  src="/sns.jpg">
			</li>
		</ul>
	</div>
	<div class = "col-md-offset-1 col-md-5">
		<% if @user.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
				<ul>
					<% @user.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<%= form_with(model: @user, local: true) do |f| %>
			<%= f.text_field :name ,class: "form-group form-control form-control-lg",:placeholder => "名前" %>
			<%= f.email_field :email ,class: "form-group form-control form-control-lg",:placeholder => "メールアドレス" %>
			<%= f.password_field :password ,class: "form-group form-control form-control-lg", :placeholder => "パスワード" %>
			<%= f.password_field :password_confirmation, class: "form-group form-control form-control-lg", :placeholder => "パスワード（再入力）" %>
			<%= f.submit "新しいアカウントを作成", class:"btn btn-primary btn-lg btn-block" %>
		<% end %><hr>
		<%= link_to "ログイン", new_session_path, class:"btn btn-success btn-lg btn-block"  %>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<% if @user.id == current_user.id %>
  <%= link_to "プロフィールを編集", edit_user_path(current_user.id), class:"btn btn-success" %>
  <%= link_to '投稿する', new_post_path, class:"btn btn-primary" %>
<% end %>